language: ruby
os: linux
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.8
jobs:
  include:
    - rvm: 2.7
      script:
        - python3 --version
        - python3 -m pip install setuptools
        - ruby -v
        - gem install rubygems-bundler
        - cd tests
        - bundle
        - sudo ruby ci.rb

    - rvm: 2.6
      script:
        - python3 --version
        - python3 -m pip install setuptools
        - ruby -v
        - gem install rubygems-bundler
        - cd tests
        - bundle
        - sudo ruby ci.rb

    - rvm: 2.5
      script:
        - python3 --version
        - python3 -m pip install setuptools
        - ruby -v
        - gem install rubygems-bundler
        - cd tests
        - bundle
        - sudo ruby ci.rb

