language: python
os: linux
dist: xenial
jobs:
  include:
    - rvm: 2.7
      script:
        - ruby -v
        - tests/ci.sh
    - rvm: 2.6
      script:
        - ruby -v
        - tests/ci.sh
    - rvm: 2.5
      script:
        - ruby -v
        - tests/ci.sh

