language: ruby
os: linux
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.8
jobs:
  include:
    - rvm: 2.7
      script:
        - python3.8 --version
        - python3.8 -m pip install setuptools
        - ruby -v
        - gem install coveralls
        - gem install simplecov
        - sudo ruby tests/ci.rb

    - rvm: 2.6
      script:
        - python3.8 --version
        - python3.8 -m pip install setuptools
        - ruby -v
        - gem install coveralls
        - gem install simplecov
        - sudo ruby tests/ci.rb

    - rvm: 2.5
      script:
        - python3.8 --version
        - python3.8 -m pip install setuptools
        - ruby -v
        - gem install coveralls
        - gem install simplecov
        - sudo ruby tests/ci.rb

