language: ruby
os: linux
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.8
  - python3 --version
  - python3 -m pip install setuptools

jobs:
  include:
    - rvm: 2.7
      script:
        - ruby -v
        - gem install bundler -v 2.2.15
        - cd tests
        - bundle
        - bundle exec ruby ./ci.rb

    - rvm: 2.6
      script:
        - ruby -v
        - gem install bundler -v 2.2.15
        - cd tests
        - bundle
        - bundle exec ruby ./ci.rb

    - rvm: 2.5
      script:
        - ruby -v
        - gem install bundler -v 2.2.15
        - cd tests
        - bundle
        - bundle exec ruby ./ci.rb

