language: ruby
os: linux
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
jobs:
  include:
    - rvm: 2.7
      script:
        - python3 --version
        - ruby -v
        - tests/ci.sh
    - rvm: 2.6

      script:
        - python3 --version
        - ruby -v
        - tests/ci.sh
    - rvm: 2.5

      script:
        - python3 --version
        - ruby -v
        - tests/ci.sh

