#!/bin/sh

echo "START"
clean_up() {
  rm ruby.bin1
  rm ruby.bin2
  rm python.bin1
  rm python.bin2
}

# cd into tests directory and install bare-py
cd $1 # from ./ci.rb
cd "bare-py"
python3 setup.py install > /dev/null
cd ..

# Generate python classes
bare demo.schema demo.py

# Run ruby / python scripts

./compat.rb ruby.bin1 ruby.bin2
python3 ./compat.py python.bin1 python.bin2

if cmp ruby.bin1 python.bin1; then
  echo "Ruby and python implementations match for first test"

  if cmp ruby.bin2 python.bin2; then
    echo "Ruby and python implementations match for second test"
  else
    >&2 echo "Ruby and python bare implementations do not match"
    clean_up
    exit 255
  fi
else
  >&2 echo "Ruby and python bare implementations do not match"
  clean_up
  exit 255
fi

clean_up
exit 0

